name       : ulauncher
version    : 5.15.2
release    : 13
source     :
    - https://github.com/Ulauncher/Ulauncher/releases/download/5.15.2/ulauncher_5.15.2.tar.gz : b22337ee77485d5da0ff45ee99c8d94e701aba98e0c78a347b5f6a82baca88d7
homepage   : https://ulauncher.io/
license    : GPL-3.0-or-later
component  : desktop
summary    : Linux Application Launcher
description: |
    Ulauncher is a fast application launcher for Linux. It's is written in Python, using GTK+.
builddeps  :
    - python-distutils-extra
rundeps    :
    - keybinder
    - python-gobject
    - python-inotify
    - python-levenshtein
    - python-pygithub
    - python-websocket-client
    - python3-dbus
    - pyxdg
setup      : |
    %patch -p1 < $pkgfiles/shutup-distutils.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -r $installdir/usr/share/doc

    # We don't have wmctrl because it is DOA
    rm -f $installdir/usr/bin/ulauncher-toggle
