name       : ulauncher
version    : 5.14.1
release    : 4
source     :
    - https://github.com/Ulauncher/Ulauncher/releases/download/5.14.1/ulauncher_5.14.1.tar.gz : 28dcf822f21c026555fea70f7034005f4ab0f6887db5aa978b25df492ca422f6
homepage   : https://ulauncher.io/
license    : GPL-3.0-or-later
component  : desktop
summary    : Linux Application Launcher
description: |
    Ulauncher is a fast application launcher for Linux. It's is written in Python, using GTK+.
builddeps  :
    - python-distutils-extra
rundeps    :
    - keybinder
    - python-gobject
    - python-inotify
    - python-levenshtein
    - python-websocket-client
    - python3-cairo
    - python3-dbus
    - pyxdg
setup      : |
    %patch -p1 < $pkgfiles/shutup-distutils.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -r $installdir/usr/share/doc
