name       : ulauncher
version    : 5.12.2
release    : 2
source     :
    - https://github.com/Ulauncher/Ulauncher/releases/download/5.12.2/ulauncher_5.12.2.tar.gz : 14bb80f45115527938dca214aea665e34864c23beb060a099fbccea7ea2fa99b
homepage   : https://ulauncher.io/
license    : GPL-3.0-or-later
component  : desktop
summary    : Linux Application Launcher
description: |
    Ulauncher is a fast application launcher for Linux. It's is written in Python, using GTK+.
builddeps  :
    - python-distutils-extra
rundeps    :
    - keybinder
    - python-gobject
    - python-inotify
    - python-levenshtein
    - python-websocket-client
    - python3-cairo
    - python3-dbus
    - pyxdg
setup      : |
    sed -i "s/version='%VERSION%'/version='${version}'/g" setup.py
    %patch -p1 < $pkgfiles/shutup-distutils.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -r $installdir/usr/share/doc
