name       : ulauncher
version    : 5.14.0
release    : 3
source     :
    - https://github.com/Ulauncher/Ulauncher/releases/download/5.14.0/ulauncher_5.14.0.tar.gz : 03bdb2a16eadbb277514a9c38a29b351da72c805b1692b4560ca14bf3e2cc465
homepage   : https://ulauncher.io/
license    : GPL-3.0-or-later
component  : desktop
summary    : Linux Application Launcher
description: |
    Ulauncher is a fast application launcher for Linux. It's is written in Python, using GTK+.
builddeps  :
    - python-distutils-extra
rundeps    :
    - keybinder
    - python-gobject
    - python-inotify
    - python-levenshtein
    - python-websocket-client
    - python3-cairo
    - python3-dbus
    - pyxdg
setup      : |
    sed -i "s/version='%VERSION%'/version='${version}'/g" setup.py
    %patch -p1 < $pkgfiles/shutup-distutils.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -r $installdir/usr/share/doc
