name       : ulauncher
version    : 5.14.3
release    : 5
source     :
    - https://github.com/Ulauncher/Ulauncher/releases/download/5.14.3/ulauncher_5.14.3.tar.gz : 8bd2d419dada1513b1b32c898c134f3cf5975e5ba97a5812645be153f554e8b9
homepage   : https://ulauncher.io/
license    : GPL-3.0-or-later
component  : desktop
summary    : Linux Application Launcher
description: |
    Ulauncher is a fast application launcher for Linux. It's is written in Python, using GTK+.
builddeps  :
    - python-distutils-extra
rundeps    :
    - keybinder
    - python-gobject
    - python-inotify
    - python-levenshtein
    - python-websocket-client
    - python3-dbus
    - pyxdg
setup      : |
    %patch -p1 < $pkgfiles/shutup-distutils.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -r $installdir/usr/share/doc
