name       : ulauncher
version    : 5.14.4
release    : 7
source     :
    - https://github.com/Ulauncher/Ulauncher/releases/download/5.14.4/ulauncher_5.14.4.tar.gz : a1018a9c6fa5698908a06baf2b997d1628aa74260063633f19c18f44f10001a7
homepage   : https://ulauncher.io/
license    : GPL-3.0-or-later
component  : desktop
summary    : Linux Application Launcher
description: |
    Ulauncher is a fast application launcher for Linux. It's is written in Python, using GTK+.
builddeps  :
    - python-distutils-extra
rundeps    :
    - keybinder
    - python-gobject
    - python-inotify
    - python-levenshtein
    - python-websocket-client
    - python3-dbus
    - pyxdg
setup      : |
    %patch -p1 < $pkgfiles/shutup-distutils.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -r $installdir/usr/share/doc
