name       : ulauncher
version    : 5.11.0
release    : 1
source     :
    - https://github.com/Ulauncher/Ulauncher/releases/download/5.11.0/ulauncher_5.11.0.tar.gz : c4433bb06d0d456a2e0eee8dc4d03de164f273290484f2380728c3936ca31e3a
homepage   : https://ulauncher.io/
license    : GPL-3.0-or-later
component  : desktop
summary    : Linux Application Launcher
description: |
    Ulauncher is a fast application launcher for Linux. It's is written in Python, using GTK+.
builddeps  :
    - python-distutils-extra
rundeps    :
    - keybinder
    - python-gobject
    - python-inotify
    - python-levenshtein
    - python-websocket-client
    - python3-cairo
    - python3-dbus
    - pyxdg
setup      : |
    sed -i "s/version='%VERSION%'/version='${version}'/g" setup.py
    %patch -p1 < $pkgfiles/shutup-distutils.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -r $installdir/usr/share/doc
